services:
  postgres-db:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: trading_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - trading-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - trading-network
    depends_on:
      - postgres-db

  redis:
    image: redis:7-alpine
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - trading-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - trading-network

  trading-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-api
    restart: no
    depends_on:
      - postgres-db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/trading_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: user123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_TIMEOUT: 60000
    ports:
      - "8080:8080"
    networks:
      - trading-network

volumes:
  postgres-data:
  pgadmin-data:
  redis-data:

networks:
  trading-network:


