spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/trading_app_dev
    username: postgres
    password: dev123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: DEBUG
