spring.application.name=trading_app
server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://postgres-db:5432/trading_app
spring.datasource.username=postgres
spring.datasource.password=user123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql: true


stripe.api.key=your_stripe_api_key
razorpay.api.key=your_razorpay_api_key
stripe.api.secret=your_stripe_api_secret
razorpay.api.secret=your_razorpay_api_secret
